#!/bin/bash
yum install -y httpd
yum install -y zlib-devel epel-release python3 python3-devel mysql-devel httpd-devel
yum -y groupinstall "Development Tools"
yum update -y

# BUILD MOD_WSGI AND INSTALL
wget "https://github.com/GrahamDumpleton/mod_wsgi/archive/4.5.14.tar.gz"
tar -xzf '4.5.14.tar.gz'
cd ./mod_wsgi-4.5.14
./configure --with-python=/usr/bin/python3.7
make
make install
cd ..
rm -rf mod_wsgi-4.5.14
rm 4.5.14.tar.gz

rm -rf /var/www/wordcount/*
